// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package routeguide

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpeakClient is the client API for Speak service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpeakClient interface {
	SayHello(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloAck, error)
}

type speakClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeakClient(cc grpc.ClientConnInterface) SpeakClient {
	return &speakClient{cc}
}

func (c *speakClient) SayHello(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloAck, error) {
	out := new(HelloAck)
	err := c.cc.Invoke(ctx, "/speak.Speak/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpeakServer is the server API for Speak service.
// All implementations must embed UnimplementedSpeakServer
// for forward compatibility
type SpeakServer interface {
	SayHello(context.Context, *Hello) (*HelloAck, error)
	mustEmbedUnimplementedSpeakServer()
}

// UnimplementedSpeakServer must be embedded to have forward compatible implementations.
type UnimplementedSpeakServer struct {
}

func (UnimplementedSpeakServer) SayHello(context.Context, *Hello) (*HelloAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSpeakServer) mustEmbedUnimplementedSpeakServer() {}

// UnsafeSpeakServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeakServer will
// result in compilation errors.
type UnsafeSpeakServer interface {
	mustEmbedUnimplementedSpeakServer()
}

func RegisterSpeakServer(s grpc.ServiceRegistrar, srv SpeakServer) {
	s.RegisterService(&Speak_ServiceDesc, srv)
}

func _Speak_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeakServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/speak.Speak/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeakServer).SayHello(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

// Speak_ServiceDesc is the grpc.ServiceDesc for Speak service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Speak_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speak.Speak",
	HandlerType: (*SpeakServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Speak_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "speak/speak.proto",
}
